/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_root_jnidemo_MainActivity */

#ifndef _Included_com_example_root_jnidemo_MainActivity
#define _Included_com_example_root_jnidemo_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_root_jnidemo_MainActivity
 * Method:    getDataFromCCode
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_root_jnidemo_MainActivity_getDataFromCCode
  (JNIEnv *, jobject);

/*
 * Class:     com_example_root_jnidemo_MainActivity
 * Method:    putDataToJavaCode
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_root_jnidemo_MainActivity_putDataToJavaCode
  (JNIEnv *, jobject);

/*
 * Class:     com_example_root_jnidemo_MainActivity
 * Method:    putDataToJavaCodeWithParams
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_example_root_jnidemo_MainActivity_putDataToJavaCodeWithParams
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_example_root_jnidemo_MainActivity
 * Method:    putDataToJavaCodeWithParamsAndReturn
 * Signature: (Ljavajava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_example_root_jnidemo_MainActivity_putDataToJavaCodeWithParamsAndReturn
  (JNIEnv *, jobject, jstring);
a

#ifdef __cplusplus
}
#endif
#endif
